### ISSUE TITLE
Support for other file types

### ISSUE THREAD

**Issue by himynamesdave** [signalscorps/stixify#5]
In addition to plaintext, should support other file types (including file parsing)

**Comment by shanthanu9** [comment]
* Markdown (`.md`)
* Plain text (`.txt`)
* CSV (`.csv`)
* XML (`.xml`)
* JSON (`.json`)
* PDF (`.pdf`)
* Microsoft Word (`.doc`, `.docx`)
* Microsoft Excel (`.xls`, `.xlsx`)

Is support for the above file types sufficient?

**Comment by himynamesdave** [comment]
@shanthanu9 correct

**Comment by himynamesdave** [comment]
@shanthanu9 currently missing logic for parsing tags in md, json, xml
